 @foreach($distributors as $key=>$distributor)
 <tr>
     <td>{{$key+1}}</td>
     <td>{{$distributor->joining_date}}</td>
     <td>{{$distributor->activate_date}}</td>
     <td>{{$distributor->distributor_tracking_id}}</td>
     <td>{{$distributor->name}}</td>
     <td>{{$distributor->mobile}}</td>
     <td></td>
     @if($distributor->my_sponsor)
     <td>{{$distributor->my_sponsor->distributor_tracking_id}}</td>
     <td>{{$distributor->my_sponsor->name}}</td>
     <td>{{$distributor->my_sponsor->mobile}}</td>
     @else
     <td></td>
     <td></td>
     <td></td>
     @endif
     <td></td>
     <td>
         @if($distributor->package)
         {{$distributor->package->package_name}}
         @else
         Free
         @endif
     </td>
     <td>
         @if($distributor->package)
         Activate
         @else
         Free
         @endif
     </td>
     <td>
         @if($distributor->package)
         {{$distributor->package->amount}}
         @else
         Free
         @endif
     </td>

 </tr>
 @endforeach